// Table of contents on the extension host: the update command and update on save.
// The list itself is generated by the pure code in src/shared/toc.ts.
import * as vscode from 'vscode';
import { findTocMarkers, parseTocLevels, tocBlock, type TocOptions, tocUpdate } from '../shared/toc';
import type { MarkdownEditorProvider } from './markdownEditorProvider';

export function readTocOptions(resource: vscode.Uri): TocOptions {
  const c = vscode.workspace.getConfiguration('seamlessMarkdown', resource);
  return { ...parseTocLevels(c.get<string>('toc.levels', '1..6')), ordered: c.get<boolean>('toc.ordered', false) };
}

/** The edit that brings the list between the markers up to date, or null when there is nothing to do. */
export function tocTextEdit(document: vscode.TextDocument): vscode.TextEdit | null {
  const edit = tocUpdate(document.getText(), readTocOptions(document.uri));
  if (!edit) return null;
  return vscode.TextEdit.replace(new vscode.Range(document.positionAt(edit.from), document.positionAt(edit.to)), edit.insert);
}

async function apply(document: vscode.TextDocument, edit: vscode.TextEdit): Promise<boolean> {
  const workspaceEdit = new vscode.WorkspaceEdit();
  workspaceEdit.replace(document.uri, edit.range, edit.newText);
  return vscode.workspace.applyEdit(workspaceEdit);
}

export type TocResult = 'updated' | 'unchanged' | 'missing';

/** Regenerates the list of a document. The document is left alone when the list is already right. */
export async function updateToc(document: vscode.TextDocument): Promise<TocResult> {
  if (!findTocMarkers(document.getText())) return 'missing';
  const edit = tocTextEdit(document);
  if (!edit) return 'unchanged';
  await apply(document, edit);
  return 'updated';
}

/** Inserts a table of contents at the cursor of a plain text editor, or updates the one it has. */
export async function insertTocInTextEditor(editor: vscode.TextEditor): Promise<void> {
  const document = editor.document;
  if ((await updateToc(document)) !== 'missing') return;
  const eol = document.eol === vscode.EndOfLine.CRLF ? '\r\n' : '\n';
  const block = tocBlock(document.getText(), readTocOptions(document.uri)).replace(/\n/g, eol);
  const line = document.lineAt(editor.selection.active.line);
  const blank = (n: number) => n < 0 || n >= document.lineCount || document.lineAt(n).isEmptyOrWhitespace;
  const after = blank(line.lineNumber + 1) ? '' : eol;
  if (line.isEmptyOrWhitespace) {
    await apply(document, vscode.TextEdit.replace(line.range, (blank(line.lineNumber - 1) ? '' : eol) + block + after));
  } else {
    await apply(document, vscode.TextEdit.insert(line.range.end, eol + eol + block + after));
  }
}

/**
 * Keeps the table of contents right whenever a Markdown document that has the markers
 * is saved, in this editor or in the plain text editor.
 *
 * VS Code applies the edits a will-save listener returns only if the document did not
 * change while the listener ran. That matters for the Seamless Markdown editor, which
 * sends typing in short bursts: a save that does not come from its own Save command
 * (auto save, File > Save from the menu, Save All) can arrive while the last words are
 * still in the webview. So the listener first asks every editor of the document for its
 * unsent text, which also puts that text into the file being saved, and builds the list
 * from the result. If that changed the document, the returned edits would be dropped, so
 * the list is then applied directly; otherwise it is returned as ordinary TextEdits.
 * Asking the webview is bounded (400 ms each, in parallel), well inside the time VS Code
 * gives a will-save listener. A hidden webview is not asked: it hands over its text when
 * it is hidden.
 */
export function updateTocOnSave(provider: MarkdownEditorProvider): vscode.Disposable {
  return vscode.workspace.onWillSaveTextDocument((event) => {
    const document = event.document;
    const sessions = provider.sessionsFor(document.uri);
    if (document.languageId !== 'markdown' && !sessions.length) return;
    if (!vscode.workspace.getConfiguration('seamlessMarkdown', document.uri).get<boolean>('toc.updateOnSave', true)) return;
    // Documents without the markers are not touched and their save is not delayed.
    if (!findTocMarkers(document.getText())) return;
    if (!sessions.length) {
      const edit = tocTextEdit(document);
      if (edit) event.waitUntil(Promise.resolve([edit]));
      return;
    }
    const version = document.version;
    event.waitUntil(
      (async (): Promise<vscode.TextEdit[]> => {
        await Promise.all(sessions.map((s) => s.flush()));
        const edit = tocTextEdit(document);
        if (!edit) return [];
        if (document.version === version) return [edit];
        await apply(document, edit);
        return [];
      })(),
    );
  });
}
