// Table of contents on the extension host: the update command and update on save.
// The list itself is generated by the pure code in src/shared/toc.ts.
import * as vscode from 'vscode';
import { findTocMarkers, parseTocLevels, tocBlock, type TocOptions, tocUpdate } from '../shared/toc';
import type { MarkdownEditorProvider } from './markdownEditorProvider';

export function readTocOptions(resource: vscode.Uri): TocOptions {
  const c = vscode.workspace.getConfiguration('seamlessMarkdown', resource);
  return { ...parseTocLevels(c.get<string>('toc.levels', '1..6')), ordered: c.get<boolean>('toc.ordered', false) };
}

/** The edit that brings the list between the markers up to date, or null when there is nothing to do. */
export function tocTextEdit(document: vscode.TextDocument): vscode.TextEdit | null {
  const edit = tocUpdate(document.getText(), readTocOptions(document.uri));
  if (!edit) return null;
  return vscode.TextEdit.replace(new vscode.Range(document.positionAt(edit.from), document.positionAt(edit.to)), edit.insert);
}

async function apply(document: vscode.TextDocument, edit: vscode.TextEdit): Promise<boolean> {
  const workspaceEdit = new vscode.WorkspaceEdit();
  workspaceEdit.replace(document.uri, edit.range, edit.newText);
  return vscode.workspace.applyEdit(workspaceEdit);
}

export type TocResult = 'updated' | 'unchanged' | 'missing' | 'refused';

/** Regenerates the list of a document. The document is left alone when the list is already right. */
export async function updateToc(document: vscode.TextDocument): Promise<TocResult> {
  if (!findTocMarkers(document.getText())) return 'missing';
  const edit = tocTextEdit(document);
  if (!edit) return 'unchanged';
  return (await apply(document, edit)) ? 'updated' : 'refused';
}

/** Inserts a table of contents at the cursor of a plain text editor, or updates the one it has. */
export async function insertTocInTextEditor(editor: vscode.TextEditor): Promise<void> {
  const document = editor.document;
  if ((await updateToc(document)) !== 'missing') return;
  const eol = document.eol === vscode.EndOfLine.CRLF ? '\r\n' : '\n';
  const block = tocBlock(document.getText(), readTocOptions(document.uri)).replace(/\n/g, eol);
  const line = document.lineAt(editor.selection.active.line);
  const blank = (n: number) => n < 0 || n >= document.lineCount || document.lineAt(n).isEmptyOrWhitespace;
  const after = blank(line.lineNumber + 1) ? '' : eol;
  if (line.isEmptyOrWhitespace) {
    await apply(document, vscode.TextEdit.replace(line.range, (blank(line.lineNumber - 1) ? '' : eol) + block + after));
  } else {
    await apply(document, vscode.TextEdit.insert(line.range.end, eol + eol + block + after));
  }
}

/** How long a save waits for the editor to hand over unsent typing. */
const FLUSH_LIMIT_MS = 800;

/**
 * Keeps the table of contents right whenever a Markdown document that has the markers
 * is saved, in this editor or in the plain text editor.
 *
 * Rules this listener has to live by:
 * - VS Code stops calling a will-save listener that throws or takes longer than 1.5 s a
 *   few times, so nothing here may throw and all waiting is bounded.
 * - VS Code applies the TextEdits a listener returns only if the document did not change
 *   while the listener ran; otherwise it drops them.
 * - The result is idempotent: once the list is right there is no edit, so a save can
 *   never dirty the document again and cause another save.
 *
 * Unsent typing. The Seamless Markdown editor sends typing in short bursts. Its own Save
 * command asks for the unsent text first, but File > Save from the menu and Save All do
 * not, so a save the user asked for can arrive while the last words are still in the
 * webview. For such a manual save the listener asks every editor of the document for its
 * unsent text first, which also puts that text into the file being saved, and builds the
 * list from the result. That changes the document, so the returned edits would be
 * dropped; the list is then applied directly instead. If an editor does not answer in
 * time the save goes ahead with what the document holds. A hidden webview is not asked:
 * it hands over its text when it is hidden.
 *
 * Auto save is not a moment the user chose, so it does not cut a typing burst short (that
 * would also split the undo steps): the list is built from the document as it is, and
 * the typing follows with the next save, as it always did.
 */
export function updateTocOnSave(provider: MarkdownEditorProvider): vscode.Disposable {
  const failed = (err: unknown) => provider.log(`table of contents on save: ${err instanceof Error ? err.message : String(err)}`);
  return vscode.workspace.onWillSaveTextDocument((event) => {
    try {
      const document = event.document;
      const sessions = provider.sessionsFor(document.uri);
      if (document.languageId !== 'markdown' && !sessions.length) return;
      if (!vscode.workspace.getConfiguration('seamlessMarkdown', document.uri).get<boolean>('toc.updateOnSave', true)) return;
      // Documents without the markers are not touched and their save is not delayed.
      if (!findTocMarkers(document.getText())) return;
      if (!sessions.length || event.reason !== vscode.TextDocumentSaveReason.Manual) {
        const edit = tocTextEdit(document);
        if (edit) event.waitUntil(Promise.resolve([edit]));
        return;
      }
      const version = document.version;
      event.waitUntil(
        (async (): Promise<vscode.TextEdit[]> => {
          try {
            const limit = new Promise<void>((resolve) => setTimeout(resolve, FLUSH_LIMIT_MS));
            await Promise.race([Promise.all(sessions.map((s) => s.flush())), limit]);
            const edit = tocTextEdit(document);
            if (!edit) return [];
            if (document.version === version) return [edit];
            await apply(document, edit);
          } catch (err) {
            failed(err);
          }
          return [];
        })(),
      );
    } catch (err) {
      failed(err);
    }
  });
}
